name: Terraform Pipeline
run-name: ${{ github.actor }} iniciou o pipeline
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check-format-syntax:
    name: Verificar a Sintaxe e Formatar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar o Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Inicializar Terraform
        run: terraform init

      - name: Formatar
        run: terraform fmt -recursive

      - name: Verificar Sintaxe
        run: terraform validate

  terraform-docs:
    name: Gerar Documentação (terraform-docs)
    runs-on: ubuntu-latest
    needs: check-format-syntax  # Garante que este job depende do sucesso do job 'check-format-syntax'
    if: github.event_name == 'push'

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para evitar erros ao fazer push

      - name: Configurar o Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Inicializar Terraform
        run: terraform init

      - name: Verificar Formatação
        run: terraform fmt -check -recursive

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}

      - name: Rodar Terraform Docs via Docker
        run: |
          docker run --rm \
            --volume "$(pwd):/workspace" \
            quay.io/terraform-docs/terraform-docs:latest \
            markdown table --output-file README.md --output-mode inject /workspace

      - name: Verificar se há mudanças
        run: |
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Commit e Push do README.md atualizado
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualiza documentação Terraform via GitHub Actions"
          git push